### ISSUE TITLE
Error on unsupported tls protocol

### ISSUE THREAD

**Issue by sax** [titanous/heartbleeder#10]
I'm getting the following error when attempting to use heartbleeder.

```
tls: server selected unsupported protocol version 300
```

If I can find any more information I'll add it here.

**Comment by titanous** [comment]
The server probably only supports SSLv3, the TLS library we use doesn't support SSL, only TLS >= 1.0.

**Comment by sax** [comment]
Ah, that makes sense, and gives me a lot more infomation to work on. Thank you!
