### ISSUE TITLE
README for ubuntu

### ISSUE THREAD

**Issue by AlephOne** [titanous/heartbleeder#13]
On latest Ubuntu, getting go 1.2 is a bit odd and took some Google-fu! at least for me.

I'd suggest adding to README:

For Ubuntu Saucy (13.10), to get go 1.2:
# install earlier go

apt-get install golang-go
apt-get install bzr
go get gopkg.in/niemeyer/v0/godeb
# make way for newer version of go

apt-get remove golang-go
apt-get autoremove
godeb 1.2.1
# build heartbleeder as per above

**Comment by titanous** [comment]
I added a link to godeb in the README. The instructions include links to precompiled binaries, so no need to bootstrap.
