### ISSUE TITLE
hostfile option ignored

### ISSUE THREAD

**Issue by jm3** [titanous/heartbleeder#18]
```
heartbleeder -hostfile domains.txt
Usage: heartbleeder host[:443]
```

:frowning:

**Comment by titanous** [comment]
Looks like you don't have the latest version, try redownloading/recompiling?

**Comment by jm3** [comment]
already did, twice, using the instructions on the README.

when i download the zip from github and run `go build` in the directory, it errors with:

```
# _/~/heartbleeder-master
./heartbleeder.go:91: c.WriteHeartbeat undefined (type *"github.com/titanous/heartbleeder/tls".Conn has no field or method WriteHeartbeat)
./heartbleeder.go:104: c.ReadHeartbeat undefined (type *"github.com/titanous/heartbleeder/tls".Conn has no field or method ReadHeartbeat)
```

**Comment by titanous** [comment]
Run `go get -u github.com/titanous/heartbleeder` to update.

**Comment by jm3** [comment]
NICE! That's what I needed, thank you!

**Comment by jm3** [comment]
PS. maybe add that to the readme under the Installation section?

**Comment by titanous** [comment]
Sure, done.
