### ISSUE TITLE
all releases are compiled for Mach-O 64bit

### ISSUE THREAD

**Issue by opie4624** [titanous/heartbleeder#3]
```
opie4624@thisplace:~$ ./heartbleeder-v0.3_linux-386
-bash: ./heartbleeder-v0.3_linux-386: cannot execute binary file
opie4624@thisplace:~$ file heartbleeder-v0.3_linux-386
heartbleeder-v0.3_linux-386: Mach-O 64-bit executable
```

**Comment by titanous** [comment]
Oops, looking into it.

**Comment by alouche** [comment]
@opie4624 - for the time being, wget http://gobuild.io/github.com/titanous/heartbleeder/master/linux/386 -O output.zip

Cf. http://gobuild.io/download/github.com/titanous/heartbleeder

**Comment by titanous** [comment]
@alouche I'll just link to that, thanks.

**Comment by opie4624** [comment]
@alouche Or, spin up a mac vm. ;) Thanks guys.
