### ISSUE TITLE
timeout after updating openssl

### ISSUE THREAD

**Issue by twouters** [titanous/heartbleeder#6]
Before updating openssl heartbleeder detects the vulnerability:

```
INSECURE - domain.tld:443 has the heartbeat extension enabled and is vulnerable
```

After updating openssl heartbleeder times out:

```
SECURE - timed out while waiting for a response from domain.tld
```

**Comment by titanous** [comment]
Looks like it's working, I'll tweak that message a bit.

**Comment by kuebk** [comment]
Same issue here.
